### PR TITLE
Gallery

### LINKED ISSUE #173: Create a gallery page similar to notebooks_demos index
@MathewBiddle if I recall correctly you wanted a gallery page similar to the EDS book, right? Sorry if there is an open issue for it but I could not find it. It turns out we had that in the previous incarnation of this book and I adapted it to the jupyterbook infrastructure. Here is a screenshot of what I have so far:

Screenshot from 2023-12-21 16-47-37

What do you think?

### PR DESCRIPTION
**Pull request by ocefpaf**
Version 2 of #174. I'm still trying to optimize the script to avoid the manual adjustments to the markdown file.

Closes #173 

This is not ready to be merged yet. We need to decide:

- [x] what "badges" we want: highlight package and keyword
- [ ] image placeholder for notebooks that do not have a figure: make it smaller
- [ ] Should the gallery be the only way to navigate the notebooks?
- [ ] Add the keywords in the notebook for the badges

For the last one we will experiment with a main gallery with all the notebooks in a single place, and another one for each current category we have.

### CODE REVIEW

**Comment by MathewBiddle** [comment]
>  Should the gallery be the only way to navigate the notebooks?

I like having the sidebar for folks who know where they want to go.

> what "badges" we want: highlight package and keyword

Package/tool highlighted (R, Python, Plotly, pyobis, r-obis, etc.), topical keyword (dat mgmt, data access, etc.), data service (THREDDS, ERDDAP).

LMK when your ready for review.

**Comment by ocefpaf** [comment]
> LMK when your ready for review.

It should be ready for a first pass.

**Comment by MathewBiddle** [comment]
This looks good to me. I'm curious, did you write a script to create `gallery.md`?

I'll merge and we can make any fixes as needed. Really neat feature here.

**Review by MathewBiddle — COMMENTED** [review]
approved

**Pull request merged**
