### PR TITLE
adding R nc to DwC notebook

### PR DESCRIPTION
**Pull request by MathewBiddle**
Not complete yet

### CODE REVIEW

**Comment by MathewBiddle** [comment]
xref:
- https://github.com/ioos/notebooks_demos/pull/393
- https://github.com/ioos/notebooks_demos/issues/368

**Comment by MathewBiddle** [comment]
xref: https://github.com/inbo/etn/issues/256

**Comment by MathewBiddle** [comment]
@ocefpaf we're getting close to finishing this one out. Whenever you get a chance, mind digging in and seeing if it makes sense?

The later 1/3 of the notebook is about generating a metadata record for these data. We are undecided on what content belongs in that, so I have commented it out. Please disregard for now.

**Comment by MathewBiddle** [comment]
actually, it just dawned on me that maybe this notebook is more appropriate in https://github.com/ioos/bio_data_guide to be built into the https://ioos.github.io/bio_data_guide/

**Comment by ocefpaf** [comment]
> actually, it just dawned on me that maybe this notebook is more appropriate in https://github.com/ioos/bio_data_guide to be built into the https://ioos.github.io/bio_data_guide/

👍🏽 but I'll write y two cents below. I don't have a lot to comment b/c I'm not a R person.

- Something, maybe `maps`?, is loading deprecated libraries that are no longer available on CRAN. They'll always be in conda-forge but folks trying to reproduce that outside of the conda world may have trouble. Maybe we could ask Ben what are the modern alternatives.
- I'd put the `sessionInfo()` call at the end of the notebook to improve the readability. That is kind of an appendix IMO.
- In cell 20 maybe do a 0.5 degree, or even a 0.25 degree for the limits. the map is big and the data seems to be cluttered at the centered.
- The notebook is unfinished but it already has a lot of information. Does it make sense to break it down into smaller steps?

**Comment by MathewBiddle** [comment]
> The notebook is unfinished but it already has a lot of information. Does it make sense to break it down into smaller steps?

Agreed. There is a lot of printing of the contents of variables and netCDF stuff. Maybe that should be reduced and could help with the overwhelming amount of information?

Are there some small nuggets we can pull out of this notebook to add to the CodeLab? Initially I wanted to add this notebook here because I wanted to highlight using netCDF in the R language (I heard some comments that they didn't play nicely together). 

I propose that this notebook, in it's entirety, gets moved over to bio_data_guide as an R markdown notebook. Then, we simplify the notebook here to reading netCDF data from R and making a map (cells 1-11).

**Comment by ocefpaf** [comment]
> Agreed. There is a lot of printing of the contents of variables and netCDF stuff. Maybe that should be reduced and could help with the overwhelming amount of information?

If outputting just a few lines for some tables still conveys the message, that should help a bit.
 
> Are there some small nuggets we can pull out of this notebook to add to the CodeLab? Initially I wanted to add this notebook here because I wanted to highlight using netCDF in the R language (I heard some comments that they didn't play nicely together).

netCDF problems are always hard to understand without more context. Is it installation? Are folks compiling from source? Or maybe v3 vs v4? netCDF does plays with R but the devil is in the details and folks who are not used to it may hit a wall. 

> I propose that this notebook, in it's entirety, gets moved over to bio_data_guide as an R markdown notebook. Then, we simplify the notebook here to reading netCDF data from R and making a map (cells 1-11).

+1, and we can link them to help direct traffic from the short version to the full one and vice-versa.

**Comment by MathewBiddle** [comment]
Okay, I simplified the notebook and removed all the DwC formatting and metadata generation stuff. 

I'm thinking the map would be nice to include some depiction of the quality of each point to highlight the odd appearance off Hawaii. 

Maybe we could use ERDDAPs interpolate feature to show what water temperatures were during this animals movement?

**Comment by MathewBiddle** [comment]
I feel better about the notebook now. Using the animal time, lat, and lon, we ping coastwatch ERDDAP for SST data using the interpolate feature. 

Now I think the notebook should be moved to data_analysis_and_visualizations? Maybe data_access? I'm not sure. 

Comments are welcome!

**Comment by MathewBiddle** [comment]
@ocefpaf I moved it, renamed it, added some context. When you get a chance, mind taking a look so we can finish it out? Feel free to put on your oceanographer hat for the last bit in using the MURSST data. I'd like to show something more meaningful than a timeseries of temperature data...

**Comment by ocefpaf** [comment]
Some (very minor) nitpicks:

- I would remove comments that can be inferred from the code, like `#Load libraries` , `#includes stringr`, `#fname = str_split_i(url, "/", i=-1)` and others.
- the `maps` package is triggering a deprecation warning. I'm not a R users so I don't know if it is a matter of just wainting for an update or if we must find a substitute for it.
- cell[3]: prints a lot of metadata! That makes it a bit hard to read the notebook. Maybe we should print only the `summary` or the `title`?
- cel[10]: I'm not sure that plot is useful.
- cell[11]: Maybe overlaid on the SST image? 
- cell[11]: The markdown says `with the colors dependent on time` but I don't see any colors, right?

My oceanographic hat is stored someplace I cannot find but... What if you plot the sharks position with a color coded SST circle? Similar to what we did in https://ioos.github.io/ioos_code_lab/content/code_gallery/data_analysis_and_visualization_notebooks/2021-10-25-ERDDAP-interpolate.html ?

**Comment by MathewBiddle** [comment]
Thanks @ocefpaf! I think I addressed all your comments. We could probably make the mapping a function which might clean up the code. 

I tried to replicate the map in the notebook you referenced.

**Comment by ocefpaf** [comment]
I'm not an R expert but it LGTM!

**Comment by MathewBiddle** [comment]
@laurabrenskelle I just ran through this notebook and the NCEI data access url changed from nodc -> ncei. The notebook has been updated to reflect the change. Do you mind having a look at it?

**Comment by laurabrenskelle** [comment]
I ran through this and it looks good to me.

**Comment by MathewBiddle** [comment]
Thanks @laurabrenskelle. @ocefpaf let's merge this and move on! :)

**Comment by ocefpaf** [comment]
I'll create the gallery entry for it in a bit.

**Pull request merged**
