### PR TITLE
update lock file

### PR DESCRIPTION
**Pull request by ocefpaf**
I also want to investigate some of the CI failures here.

### CODE REVIEW

**Comment by ocefpaf** [comment]
`2016-11-16-CF-UGRID-SGRID-conventions.ipynb` is failing b/c the https://geoport.whoi.edu/thredds/catalog/coawst_4/use/fmrc/catalog.html?dataset=coawst_4/use/fmrc/coawst_4_use_best.ncd endpoint seems to be down. I'm not sure if it moved, is down permanently, or if it is a temporary issue. I'm looking into other datasets that could be used here instead.

**Comment by ocefpaf** [comment]
`jupyterbook/content/code_gallery/data_access_notebooks/2017-06-12-NCEI_RA_archive_history.ipynb` failed with `HTTPError: HTTP Error 503: Service Unavailable`. This is most likely temporary, merging this one so we can move forward with other PRs.

**Comment by MathewBiddle** [comment]
> `2016-11-16-CF-UGRID-SGRID-conventions.ipynb` is failing b/c the https://geoport.whoi.edu/thredds/catalog/coawst_4/use/fmrc/catalog.html?dataset=coawst_4/use/fmrc/coawst_4_use_best.ncd endpoint seems to be down. I'm not sure if it moved, is down permanently, or if it is a temporary issue. I'm looking into other datasets that could be used here instead.

We seem to run into this a lot with these notebooks. Would it be worthwhile to write a test Action that tests all the endpoints we hit to ensure they are functioning properly? Then, run that before the CI's?

It's difficult to highlight IOOS data services and tools when some of the services are down...

**Comment by ocefpaf** [comment]
> We seem to run into this a lot with these notebooks.

In a way, the notebook itself is a test for the endpoint. Separating the endpoint test may hinder the failure when it happens during download time or accessing a variable.

> It's difficult to highlight IOOS data services and tools when some of the services are down...

Indeed. We should however have a list of essential/important services that we could track in another repo and have some diagnostics for them.

**Comment by MathewBiddle** [comment]
Great points!

**Pull request merged**
