### PR TITLE
add google stats and point to the new repo

### PR DESCRIPTION
**Pull request by ocefpaf**
@MathewBiddle can you take a look at this one?

### CODE REVIEW

**Comment by ocefpaf** [comment]
- [ ] zenodo DOI
- [ ] add warnings on notebooks that do not run
- [ ] check the data files for the notebooks that read from the data folder

**Comment by ocefpaf** [comment]
@MathewBiddle I guess I'll need adim rights for the zenodo DOI. Can you access [this page](https://zenodo.org/account/settings/github/repository/ioos/ioos_code_lab)?

zenodo

**Comment by MathewBiddle** [comment]
For some reason it wasn't 'enabled'. I've done that now:
image
You should be able to go to that link and finish it out.

**Comment by ocefpaf** [comment]
> You should be able to go to that link and finish it out.

Nope. I think I cannot access without admin rights :-/

**Comment by MathewBiddle** [comment]
You are now an Admin. Should make things easier in the future too.

**Pull request merged**
