### PR TITLE
adding new notebook for CKAN API query

### LINKED ISSUE #47: Query IOOS CKAN API for specific free text variable
* xref: https://github.com/ioos/notebooks_demos/issues/405

@mwengren has some solid examples here: https://github.com/mwengren/notebooks-dev/tree/master/ioos_ckan_catalog

Lets make a plan for adding them to the code lab.

### PR DESCRIPTION
**Pull request by MathewBiddle**
closes #47

### CODE REVIEW

**Comment by ocefpaf** [comment]
You can remove the COLAB badge, jupyterbook will add that in as a dropown option for us.

**Comment by MathewBiddle** [comment]
Do we need all that install stuff too?

**Comment by MathewBiddle** [comment]
I will be presenting this notebook tomorrow around 1pm ET. Probably too soon to push it out live for that though.

**Comment by ocefpaf** [comment]
> I will be presenting this notebook tomorrow around 1pm ET.

Online? I'd love to see that.

**Comment by MathewBiddle** [comment]
I feel pretty confident that this is ready to go. I needed to add `ckanapi` to the environment.

It takes a while to run because it's pulling in data from 422 datasets...

@ocefpaf LMK if this is good to merge.

**Comment by MathewBiddle** [comment]
Looks like 3 of the tests are failing. I think it's because of broken urls...

**Comment by ocefpaf** [comment]
> Looks like 3 of the tests are failing. I think it's because of broken urls...

Yep. Nothing related to this PR. We are good to merge this one.

**Pull request merged**
