### PR TITLE
Adding Pyobis example notebook

### LINKED ISSUE #106: pyobis example notebook using known dataset ids
- [ ] What is language(s) for used in the example?
   - Python
- [ ] Is it focused on a particular module/software or an IOOS data service?
   - pyobis
- [ ] Can you provide a minimum example of the expected code and results in a notebook?
   - https://github.com/MathewBiddle/sandbox/blob/main/notebooks/IOOS_occurrences_in_OBIS.ipynb

Please provide a detailed description of the suggested example below:
The example notebook, provided above, uses two google spreadsheets (which contain OBIS dataset IDs affiliated with various IOOS efforts) to collect occurrence observations in OBIS. I would like to make a notebook that does the same thing, but uses the pyobis package to gather data. 

Maybe we can think of a more logical way to manage the dataset IDs too? I don't think we can do searches in OBIS for related keywords, but could be possible?

It would like to see a heatmap of where affiliated IOOS networks have contributed occurrence observations.

### PR DESCRIPTION
**Pull request by MathewBiddle**
closes #106

### CODE REVIEW

**Comment by ocefpaf** [comment]
pre-commit.ci autofix

**Review by ocefpaf — COMMENTED** [review]
Minor comments:

- In cell [5] you have a comment for the future. Maybe, to keep the notebook "clean," that could be an issue instead of a commented out cell.
- The tables tables in the notebook are quite big. If they are only for a quick data check/demo, maybe consider using just a few rows like `df_meta.head(5)` instead of all 45 rows. (Same in cell 11).
- You don't need `plt.show()` in a notebook but it doesn't hurt to leave it there.
- There seems to be some commented out debug print statement, consider removing them to improve the notebook readability.
- A comment that describes what is being done decreases readability instead of improving it I would remove the one at the top of cell 17 b/c the next cell is almost the same sentence in s highly legible code.
- Everything after cell 18 is commented out. If we cannot run maybe consider removing it.

**Comment by ocefpaf** [comment]
> pre-commit.ci autofix

@MathewBiddle you'll have to do a `git pull` b/c I asked pre-commit to perform a fix automated fixes. If that doesn't work don't worry, just force push what you have and we can re-run pre-commit later.

**Comment by MathewBiddle** [comment]
@ocefpaf I was hoping to only use pyobis for this notebook, but it wasn't quite ready yet. I made some work arounds and added some context. Let me know what you think. 

At the end of the notebook, what I tried to do is repeat this figure [1] from [2]. But, the latitudes on the map don't match the latitudes on the histogram (so I did some fiddling). We've tried figuring it out before, but never quite finished it up (see last cell in [3]. 

[1] - image

[2] - https://github.com/iobis/pyobis/blob/main/notebooks/biodiversity_mapping.ipynb

[3] - https://github.com/MathewBiddle/bio_ice/blob/main/create_map_from_OBIS_API.ipynb

**Comment by MathewBiddle** [comment]
@ocefpaf I think I addressed your comments.

**Comment by ocefpaf** [comment]
The `re`, `sys`, and `os` modules are imported but unused.

PS: In notebooks we break the rule of imports at the top and usually import them at first cell that uses them to help show its use and track what is being used and what was abandoned along the way.

**Comment by MathewBiddle** [comment]
> Also, the file US_MBON_bounding_boxes_20230315.geojson is not used and creating it is not too slow. We can demonstrate how to save it but no need to track it on GH IMO.

Agreed. my mistake on that one.

**Comment by MathewBiddle** [comment]
I'm thinking we should remove cell 9 and the italicized text in the markdown above. That cell is only returning the first 10k entries and exemplifies the failing API response, not something we want to promote at the moment.

**Comment by ocefpaf** [comment]
> I'm thinking we should remove cell 9 and the italicized text in the markdown above. That cell is only returning the first 10k entries and exemplifies the failing API response, not something we want to promote at the moment.

Done!

**Comment by MathewBiddle** [comment]
I'm okay with merging this! Thanks for all your help on this one!

**Comment by ocefpaf** [comment]
> I'm okay with merging this! Thanks for all your help on this one!

Just waiting the CIs to merge this one and #131.

**Pull request merged**
