### PR TITLE
fix broken link

### PR DESCRIPTION
**Pull request by ocefpaf**
xref.: https://github.com/ioos/ioos-atn-data/pull/83

### CODE REVIEW

**Comment by ocefpaf** [comment]
@MathewBiddle I'm using https://ioos.github.io/ioos-atn-data/atn-sat-telem-specification-v1-0.html#atn-satellite-trajectory-specification-attributes specifications as an alternative for the removed CDL file. I'm not sure that is the best, let me know if that link is OK.

**Comment by MathewBiddle** [comment]
Maybe this would be better? https://ioos.github.io/ioos-atn-data/atn-sat-telem-specification-v1-0.html#example-dataset

**Comment by ocefpaf** [comment]
> Maybe this would be better? https://ioos.github.io/ioos-atn-data/atn-sat-telem-specification-v1-0.html#example-dataset

Done!

**Comment by ocefpaf** [comment]
It seems that now https://www.ndbc.noaa.gov/ioosstats/ is broken :-/

**Comment by ocefpaf** [comment]
All green!

**Pull request merged**
