### PR TITLE
adding GTS widget notebook

### PR DESCRIPTION
**Pull request by MathewBiddle**
need to debug still

### CODE REVIEW

**Comment by MathewBiddle** [comment]
xref: 
- https://github.com/ioos/notebooks_demos/pull/398

**Comment by MathewBiddle** [comment]
Maybe it's okay? This branch on my fork was really behind so I merged it with main. Now it looks like 65 files changed?! Not what I was going for. Git eludes me today :/

**Comment by MathewBiddle** [comment]
Did a rebase fix it?

**Comment by ocefpaf** [comment]
> Did a rebase fix it?

Argh... This passed under my radar when I switched focus to compliance-checker. I rebased and moved it to the right directory. If you are going to work some more I suggest a git pull before you do anything. This notebook is no longer in `Code Gallery`, with space and title case, it is under `code_gallery` now, where the page builder will look for it.

**Comment by MathewBiddle** [comment]
This is good to merge if you think it looks good. I'm done w/ my edits.

**Comment by ocefpaf** [comment]
The way it is we have zero changes :-/

I wonder if the notebook you had here was already commit or if we made a mistake somewhere.

**Comment by MathewBiddle** [comment]
Okay, forgot to push my version. Sorry for the mix-up, should be alright now.

**Comment by ocefpaf** [comment]
The failure in FAILED jupyterbook/content/code_gallery/data_access_notebooks/2016-12-19-exploring_csw.ipynb seems to be a temporary network one. Merging...

**Pull request merged**
