### PR TITLE
fixing the NCEI RA archive notebook

### PR DESCRIPTION
**Pull request by MathewBiddle**
- API change
- plotting change

### CODE REVIEW

**Comment by MathewBiddle** [comment]
xref:
- https://github.com/ioos/notebooks_demos/pull/406

**Comment by MathewBiddle** [comment]
@ocefpaf This should be ready to merge. Hopefully I've fixed all the problems, including the formatting.

**Comment by ocefpaf** [comment]
I wonder where these conflicts are coming from. Conflicts with notebooks are really hard to manage. I usually just rebase and overwrite with my own version or close the PR and open a new one.

**Comment by MathewBiddle** [comment]
Think I fixed the conflicts.

**Comment by MathewBiddle** [comment]
Turns out I had the old `Code Gallery` directory and didn't update the branch to the most recent organization. Everything should be okay now. LMK if anything goes haywire.

**Comment by MathewBiddle** [comment]
@ocefpaf, I'm confused here. Looks like this PR was merged and the notebook updated. However, it looks like something isn't right with the GHA as the branch [gh-pages](https://github.com/ioos/ioos_code_lab/tree/gh-pages/_sources/content) hasn't been updated since Sept. 2nd. 

Is there something that needs to be followed up on?

**Comment by ocefpaf** [comment]
The notebook test should not influence the page publication. That is the main reason why we don't re-run the notebooks to publish them. Our notebooks rely on services that may fail when the CI is running and/or datasets that moved.

 I think I nailed it in #31. There was still one reference to `master` that should be `main`.

**Pull request merged**
