### PR TITLE
adding SCCOOS HABS R notebook

### PR DESCRIPTION
**Pull request by MathewBiddle**
adding sccoos HABs notebook

### CODE REVIEW

**Comment by MathewBiddle** [comment]
xref:
- https://github.com/ioos/notebooks_demos/pull/370
- https://github.com/ioos/notebooks_demos/issues/365

**Comment by MathewBiddle** [comment]
@ocefpaf this notebook is close. I can't figure out how to render the maps to be interactive on the code_lab website, however.

**Comment by ocefpaf** [comment]
> I can't figure out how to render the maps to be interactive on the code_lab website, however.

This is R, right? I'm not sure if there is anything special. Let me try...

**Comment by MathewBiddle** [comment]
Oh right, this was developed a while ago! I'll work on fixing this.

**Comment by MathewBiddle** [comment]
I __think__ I fixed it. 😢

**Comment by ocefpaf** [comment]
Regarding the map, no need for the save+display. Just the `m` output is enough to render it on Jupyter:

Screenshot from 2023-05-03 12-20-54


but you may need to click on the Save Notebooks Widget State to make available for rendering in the final page.

Screenshot from 2023-05-03 12-21-54

**Comment by MathewBiddle** [comment]
oh dear. I think I really broke things here...

**Comment by ocefpaf** [comment]
> oh dear. I think I really broke things here...

Screenshot from 2023-05-03 12-41-41

Bad rebase. No problem. I'd just copy the notebook and start a new PR.

**Comment by MathewBiddle** [comment]
see #139

**Pull request closed without merging**
